POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@gmail.com",
    "password": "admin54321"
}

### login
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json
Authorization: Bearer

{
    "email": "admin@gmail.com",
    "password": "admin54321"
}

### users
GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQG1haWwuY29tIiwiaWQiOjEsImlhdCI6MTcwNjQ5NzIwOCwiZXhwIjoxNzA2NDk3MjY4fQ.j94OhrhuI79mB2Y-8sflI9RjiiPTJyw_PYerCF_r2KI